Provide ‘alertController.view.tintColor’ property
RxSwiftCommunity/RxAlert pull request #54
Opened 2021-09-12 15:09 UTC by ShenYj

- [x] Provide ‘alertController.view.tintColor’ property

2021-09-12 17:03 UTC, ShenYj reviewed
provide to set tintColor for alertController

like this:
<img width="284" alt="截屏2021-09-14 下午3 26 12" src="https://user-images.githubusercontent.com/15159923/133213963-82ff9d6a-d2dd-4ba7-9306-5b0ee1bfd416.png">

2021-10-06 03:25 UTC, keisukeYamagishi requested changes

2021-10-06 03:25 UTC, keisukeYamagishi commented on RxAlert/UIViewController+.swift
> +               tintColor: UIColor? = nil ) -> Observable<OutputAction>
`tintColor: UIColor? = nil )` 
It contains a space after the nil.
It's a small detail, but could you please remove it?

2021-10-06 03:25 UTC, keisukeYamagishi commented on RxAlertExample/ViewController.swift
> +                     tintColor: nil)
We have nil passed to tintColor, but we think it would be better to pass some color here.
Well, maybe  `black` would be better.

2021-10-06 03:25 UTC, keisukeYamagishi commented on Podfile.lock
> +COCOAPODS: 1.10.2
With this commit, we realized that podfile.lock is unnecessary.
We will consider removing it eventually, so please do not manipulate this file for now.
Maybe the build will probably pass😎

2021-10-06 09:01 UTC, keisukeYamagishi requested changes

2021-10-06 09:01 UTC, keisukeYamagishi commented on RxAlert/UIViewController+.swift
> +               tintColor: UIColor? = .black) -> Observable<OutputAction>
please `nil` is here.
Specify black for `tintColor` in the line linked below.
https://github.com/ShenYj/RxAlert/blob/92964c18eadcf618a9b1049b5dc105562aed6e2e/RxAlertExample/ViewController.swift#L119

2021-10-06 09:23 UTC, keisukeYamagishi approved these changes
LGTM🎉

2021-10-06 09:23 UTC, merged